# Generated by Django 5.0.2 on 2024-02-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description1', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img1', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img2', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img3', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('engine', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('torque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('aboutcar', models.TextField(blank=True, max_length=1000, null=True)),
                ('img4', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img5', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img6', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img7', models.FileField(blank=True, null=True, upload_to='media/brands')),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description1', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img1', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img2', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img3', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('engine', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('torque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('aboutcar', models.TextField(blank=True, max_length=1000, null=True)),
                ('img4', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img5', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img6', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img7', models.FileField(blank=True, null=True, upload_to='media/brands')),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description1', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logo', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img1', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img2', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img3', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('engine', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('torque', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('aboutcar', models.TextField(blank=True, max_length=1000, null=True)),
                ('img4', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img5', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img6', models.FileField(blank=True, null=True, upload_to='media/brands')),
                ('img7', models.FileField(blank=True, null=True, upload_to='media/brands')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=40)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=1000)),
                ('termcond', models.BooleanField()),
            ],
        ),
    ]
