# Generated by Django 5.0.2 on 2024-02-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='description1',
            new_name='Description1',
        ),
        migrations.RenameField(
            model_name='brands',
            old_name='description1',
            new_name='Description1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description1',
            new_name='Description1',
        ),
        migrations.AlterField(
            model_name='bikes',
            name='engine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
