# Generated by Django 5.0.2 on 2024-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoto', '0002_rename_description1_bikes_description1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=40)),
                ('address', models.TextField(max_length=1000)),
                ('mobile', models.CharField(max_length=15)),
                ('termcond', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('profilepic', models.FileField(upload_to='media/brands')),
                ('bio', models.TextField(max_length=500)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
