# Generated by Django 5.0.2 on 2024-02-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoto', '0003_contact_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
